"use client";

import { Sparkles } from "lucide-react";
import { Field, FieldDescription, FieldGroup } from "./ui/field";
import { InputOTP, InputOTPGroup, InputOTPSeparator, InputOTPSlot } from "./ui/input-otp";
import { Button } from "./ui/button";
import { useState, useEffect } from "react";
import { useVerify2FACode, useResend2FACode } from "~/hooks/api/auth/auth.hook";
import { toast } from "sonner";
import { useDispatch } from "react-redux";
import { useRouter } from "next/navigation";
import { login } from "~/app/slice/userSlice";
import { cn } from "~/lib/utils";

function TwoFAInput({ userId, email, setIs2FARequired, className }: { userId: string, email: string, setIs2FARequired: (value: boolean) => void, className?: string }) {
    const [otp, setOtp] = useState("");
    const [error, setError] = useState<string | null>(null);
    const [timeLeft, setTimeLeft] = useState(300); // 5 minutes in seconds

    const dispatch = useDispatch();
    const router = useRouter();

    const { verify2FACodeAsync, isPending: isVerifying, error: verifyError } = useVerify2FACode();
    const { resend2FACodeAsync, isPending: isResending } = useResend2FACode();

    useEffect(() => {
        if (timeLeft <= 0) return;
        const timerId = setInterval(() => {
            setTimeLeft((prev) => prev - 1);
        }, 1000);
        return () => clearInterval(timerId);
    }, [timeLeft]);

    const handleResend = async () => {
        if (timeLeft > 0) return;
        try {
            await resend2FACodeAsync({ email });
            setTimeLeft(300);
            toast.success("Verification code resent successfully");
        } catch (err) {
            toast.error("Failed to resend code");
        }
    };

    const formatTime = (seconds: number) => {
        const m = Math.floor(seconds / 60);
        const s = seconds % 60;
        return `${m}:${s < 10 ? '0' : ''}${s}`;
    };

    async function onVerify2FA(e: React.FormEvent) {
        e.preventDefault();
        if (!userId || otp.length !== 6) return;
        setError(null);

        try {
            const response = await verify2FACodeAsync({ id: userId, twoFACode: otp });
            if (response.accessToken) {
                dispatch(login({ accessToken: response.accessToken, loading: false }));
                router.push("/dashboard");
            }
        } catch (error) {
            setError(verifyError?.message || "Invalid verification code");
        }
    }

    return (

        <form className="relative z-10 flex flex-col gap-8" onSubmit={onVerify2FA}>
            <FieldGroup className="gap-6">
                <div className="flex flex-col items-center gap-3 text-center">
                    <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary mb-2 ring-1 ring-primary/20">
                        <Sparkles className="h-6 w-6" />
                    </div>
                    <h1 className="text-3xl font-bold tracking-tight">Two-Factor Authentication</h1>
                    <p className="text-sm text-muted-foreground/80">
                        Enter the 6-digit verification code generated by your authenticator app.
                    </p>
                </div>

                <div className="flex justify-center py-4">
                    <InputOTP
                        maxLength={6}
                        value={otp}
                        onChange={(value) => setOtp(value)}
                    >
                        <InputOTPGroup>
                            <InputOTPSlot index={0} />
                            <InputOTPSlot index={1} />
                            <InputOTPSlot index={2} />
                        </InputOTPGroup>
                        <InputOTPSeparator />
                        <InputOTPGroup>
                            <InputOTPSlot index={3} />
                            <InputOTPSlot index={4} />
                            <InputOTPSlot index={5} />
                        </InputOTPGroup>
                    </InputOTP>
                </div>

                {error && <p className="text-xs font-medium text-red-500 text-center">{error}</p>}
                {!error && verifyError && <p className="text-xs font-medium text-red-500 text-center">{verifyError.message}</p>}

                <Field>
                    <Button type="submit" disabled={otp.length !== 6 || isVerifying} className="h-11 w-full text-base font-medium shadow-lg shadow-primary/20 transition-all hover:shadow-primary/40 cursor-pointer">
                        {isVerifying ? "Verifying..." : "Verify Code"}
                    </Button>
                </Field>

                <FieldDescription className="text-center text-sm font-medium mt-4 flex flex-col gap-3">
                    {timeLeft > 0 ? (
                        <span className="text-muted-foreground">
                            Resend code in {formatTime(timeLeft)}
                        </span>
                    ) : (
                        <button type="button" onClick={handleResend} disabled={isResending} className="text-primary hover:underline underline-offset-4 transition-all">
                            {isResending ? "Resending..." : "Resend code"}
                        </button>
                    )}
                    
                    <button type="button" onClick={() => setIs2FARequired(false)} className="text-primary hover:underline underline-offset-4 transition-all">
                        Back to login
                    </button>
                </FieldDescription>
            </FieldGroup>
        </form>
    );
}

export default TwoFAInput;
